# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_OF_OVERLAYS_DWC3_FLATTENING) += dwc3-flattening-overlay.o
dwc3-flattening-overlay-y += dwc3-flattening.o
dwc3-flattening-overlay-y += dwc3-qcom_ipq4018.dtb.o
dwc3-flattening-overlay-y += dwc3-qcom_ipq4018_8dev_jalapeno.dtb.o
dwc3-flattening-overlay-y += dwc3-qcom_ipq4019.dtb.o
dwc3-flattening-overlay-y += dwc3-qcom_ipq8064.dtb.o
dwc3-flattening-overlay-y += dwc3-qcom_sdx55.dtb.o
dwc3-flattening-overlay-y += dwc3-qcom_sdx65.dtb.o
